added multi threading
FelixKLG/ddos_client pull request #1
Opened 2023-02-08 09:36 UTC by grandmasponge

pls mistaaa felic

2023-02-09 21:19 UTC, FelixKLG requested changes
Remember to not disclose targets in commits, mod files correctly, test your code, and pick the easiest option whilst ensuring the code still makes sense.

2023-02-09 21:19 UTC, FelixKLG commented on src/ddos.rs
> +#[tokio::main]
`#[tokio::main]` only needs to be applied to fn main() because Rust does not natively support async main functions without the proc macro from tokio (or whatever else lib)

You can simply delcare the function as async and poll it with .async

2023-02-09 21:19 UTC, FelixKLG commented on src/ddos.rs
> +    let target_ipv4 = IpAddr::V4(Ipv4Addr::new(82, 0, 128, 210));
Don't hardcode IPs into things, in code like this leave it as "CHANGE ME" and use
```rs
let my_var "192.168.0.1".to_string().parse::<SocketAddr>().unwrap();
```
Note: idk if the to_string() is required.

2023-02-09 21:19 UTC, FelixKLG commented on src/main.rs
> +    let target = "https://sneakyspeedyboii.com/";
Once again don't leave targets in commits.

2023-02-09 21:19 UTC, FelixKLG commented on src/main.rs
> +    let client = client_builder.build().unwrap();
At which point would introducing Anyhow/Error-stack be worth it?

2023-02-09 21:19 UTC, FelixKLG commented on Cargo.toml
> +icmp = "0.3.0"
You added the dependency however you didn't mod the ddos.rs file in main.rs so the lib is never brought into scope and additionally none of the code in the ddos.rs is ever actually compiled.

2023-02-09 21:25 UTC, sneakyspeedyboii commented
Thanks for leaving my domain in a ddos client 👍

2023-02-10 21:03 UTC, FelixKLG approved these changes
Changes satisfactory.

2023-02-10 21:06 UTC, merged